### ISSUE TITLE
ci: 👷 add dependabot

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#361]
## Description
In order to regularily check for dependency updates, dependabot should be implemented into the repository. 
A nightly check schould be set up.

## Environment (GitHub Actions or Azure DevOps)
GitHub

## Technical Information
A process about timing between dependabot opened a PR and it has to be merged should be defined. => postponed to #384 
Add chapter to CONTRIBUTING.md to check online before adding a dependency.
Check if there is a possibility to have new dependency checked in a PR. => postponed to #384 

## Edit (while implementing)
The team agreed on:
- A max concurrent PR limit of 10, split up into the packages as of:
  - 3 PRs for the root directory 
  - 5 PRs for the component directory 
  - 1 PR for placeholders directory 
  - 1 PR for the tokens directory 
- Adding an "Auto-Approve" workflow to automatically approve dependabot PRs
```
name: (deps) Automatic PR approval
on: pull_request_target
jobs:
  automate-pullrequest-review:
    runs-on: ubuntu-latest
    steps:
      - name: Approve dependabot PR
        if: ${{ github.actor == 'dependabot[bot]' }}
        uses: andrewmusgrave/automatic-pull-request-review@0.0.5
        with:
          repo-token: ${{ secrets.PAT_RELEASE_KARL }}
          event: APPROVE
          body: 'Thank you dependabot 🎊'
```
- Adding an "Auto-Merge" as successor workflow to merge `patch` updates automatically
```
name: (deps) Automatic PR merge
on: pull_request_target
jobs:
  auto-merge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ahmadnassri/action-dependabot-auto-merge@v2.6
        with:
          target: patch
          github-token: ${{ secrets.PAT_RELEASE_KARL }}
```
## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [x] Documentation has been created/updated (if applicable)
- [ ] Implementation works successfully on `feature` branch
