### ISSUE TITLE
ci: 👷 add PR title check workflow

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#60]
## User Story
As a maintainer of the Solid Design System, I would like to automate a check of the PR titles so that all PR commits match the standard from semantic release, and therewith our versioning is stable and correct.

### Suggesed Solution
Adding a PR check workflow to the project would solve the request. See (VI devs only) https://github.com/virtualidentityag/union-investment-component-library/blob/7e2990c6eb3f68203be2a85d085680c6533625b6/.github/workflows/pr-linting.yml as an sample from an earlier UI project. 

## Environment (GitHub Actions or Azure DevOps)
Github

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Implementation works successfully on `feature` branch

**Comment by Vahid1919** [comment]
@mariohamann I don't have access to the repository linked above :( 
Is there a way I could get access or can I see the example another way?

**Comment by mariohamann** [comment]
```yaml
name: "Lint PR"

on:
  pull_request_target:
    branches:
      - integration
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Linting PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
