### ISSUE TITLE
docs: 📚 style changes in samples do not show up under "see code"

### ISSUE THREAD

**Issue by Vahid1919** [solid-design-system/solid#805]
## Description
The css for sample related to parts do not show up under "see code." This makes it confusing for users to identify where a particular change/style is coming from. 

Example: 

There is no where in the code that shows the custom css used to hide the line.

![Image](https://github.com/solid-design-system/solid/assets/63849626/bcce17c3-d443-4271-adc5-003cab3bd7a2)

![Image](https://github.com/solid-design-system/solid/assets/63849626/64d74d9a-0bc1-4cb9-bf8a-3a962eb21fb2)

## Where to put the documentation
If possible, include the css changes under the "see code". Otherwise, include a code block of the change: 

Eg: 

```css

 <style>
        sd-tab-group::part(separation) {
          display: none;
        }

        sd-tab::part(base):hover {
          border-bottom: none !important;
        }

        sd-tab-group::part(scroll-button--start),
        sd-tab-group::part(scroll-button--end) {
          border-bottom: none;
        }
      </style>

```

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch
