### ISSUE TITLE
docs: 📚 sd-tab-group samples do not show the custom css

### ISSUE THREAD

**Issue by Vahid1919** [solid-design-system/solid#866]
## Description
Samples that feature modifications to sd-tab-group involve using the css parts. 

![Image](https://github.com/solid-design-system/solid/assets/63849626/6a5442f5-0c1c-437d-8a03-889098718b02)

This css parts cannot be viewed in Storybook (not even under "show code"), hence might leave developers confused as to how this modification is being achieved. 

![Image](https://github.com/solid-design-system/solid/assets/63849626/30099108-5690-4faf-80a7-3baac8dde061)

The styles added should therefore be added in the description by using triple quotation syntax like:

```css
sd-tab-group::part(separation) {
          display: none;
        }

        sd-tab::part(base):hover {
          border-bottom: none !important;
        }

        sd-tab-group::part(scroll-button--start),
        sd-tab-group::part(scroll-button--end) {
          border-bottom: none;
        }

```

## Where to put the documentation
Storybook

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch
